### ISSUE TITLE
Доработка

### ISSUE THREAD

**Issue by Malivartti** [nicolasolenev/nicolasolenev.github.io#1]
с 22 строки calc.js можно объединить условия логическими операторами ИЛИ 
if (a === null || b === null) return;
if (!checkIsRightNumber(a) || !checkIsRightNumber(b)) {...}
Хоть и ошибка будет выводиться после ввода второго числа, это уберет дублирование кода.

**Comment by nicolasolenev** [comment]
if (a === null || b === null) return; сделать не получится, т.к. предполагается, что при вводе числа а (первого числа) пользователь может передумать вычислять что-то и захотеть закрыть калькулятор. А при объединении проверок, после отмены ввода первого числа появится окно для ввода второго числа.

if (!checkIsRightNumber(a) || !checkIsRightNumber(b)) {...} Объединить можно, в таком случае дублирование кода пропадет, но пользователь узнает позже о том, что ошибся при вводе числа =). Попробую объединить, спасибо за предложение =)
